medstat/medstat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # подключаем файл настроек
from django.conf.urls.static import static  # прописываем ссылки на статик файлы
from django.conf.urls import url
from medstat import views
from rest_framework import routers
from articles.api_views import TagViewSet, ArticleViewSet, SubscriberRequestViewSet, PageHitPopularViewSet  #, PageHitViewSet
from users.api_views import InfofileViewSet  #, ArticlesUserViewSet

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register('tag', TagViewSet)
router.register('article', ArticleViewSet)
router.register('request', SubscriberRequestViewSet)
# router.register('pagehit', PageHitViewSet)
router.register('pagehit_popular', PageHitPopularViewSet)
# router.register('articles_user', ArticlesUserViewSet)
router.register('infofile', InfofileViewSet)

urlpatterns = [
    path('', views.home_page, name='home'),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('users/', include('users.urls')),
    # path('api-tag/', include('rest_framework.urls')),
    path('api/v0/', include(router.urls)),
]

if settings.DEBUG is True:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

medstat/users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('success_verification/', views.success_verification, name='success_verification'),
    path('subscribe/<int:pk>/', views.SubscribeUpdateView.as_view(), name='subscribe'),
    path('success_subscribe/', views.success_subscribe, name='success_subscribe'),
    path('get_api_token/', views.get_api_token, name='get_api_token'),
    path('update_api_token/', views.update_api_token, name='update_api_token'),
]

medstat/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime
from django.db.models import signals
from django.urls import reverse

from rest_framework.authtoken.models import Token
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.response import Response
from django.conf import settings

# Create your models here.

# https://code.tutsplus.com/ru/tutorials/using-celery-with-django-for-background-task-processing--cms-28732
# User модель и ее параметры https://djbook.ru/rel3.0/ref/contrib/auth.html#django.contrib.auth.models.User

# https://webdevblog.ru/sovremennyj-sposob-sozdanie-polzovatelskoj-modeli-user-v-django/
class ArticlesUser(AbstractUser):
    email = models.EmailField('E-mail', max_length=100, unique=True)
    is_subscribed = models.BooleanField('Подписка на новости сайта', default=True)

    def email_len_not_null(self):  # длина email не нулевая
        if len(self.email) > 0:
            return True
        return False

    def __str__(self):
        return f'{self.email}'
        # return f'{self.email}, длина email не нулевая: {self.email_len_not_null()}'

class Infofile(models.Model):
    date_visit = models.DateTimeField('Дата посещения сайта', default=datetime.now())
    user = models.ForeignKey(ArticlesUser, on_delete=models.CASCADE)

# Здесь мы определили функцию user_post_save и связали ее с сигналом post_save
# (который запускается после сохранения модели), отправленным моделью ArticlesUser
# ТЕСТИРОВАНИЕ возможности использования сигналов
@receiver(post_save, sender = ArticlesUser)
def create_info(sender, instance, **kwargs):
    Infofile.objects.create(user=instance, date_visit=datetime.now())


# Верификация email пользователя
# https://github.com/itsvinayak/user_login_and_register/blob/master/user/views.py
# https://github.com/rasca/django-verify-email/blob/master/verify_email/views.py
# https://stackoverflow.com/questions/55578387/email-verification-in-django

# https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication
# Генерация токенов используя сигналы
# Если надо, чтобы у каждого пользователя был автоматически сгенерированный токен, можно поймать post_save сигнал пользователя.
@receiver(post_save, sender=ArticlesUser)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

medstat/users/forms.py
from django import forms
from .models import ArticlesUser
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
# from django.contrib.auth.admin import UserAdmin

class RegistrationUserForm(UserCreationForm):
    class Meta:
        model = ArticlesUser
        # fields = '__all__'
        fields = ('username', 'email', 'is_subscribed')

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = ArticlesUser
        fields = ('is_subscribed',)


# class EmailForm(forms.ModelForm):
#     class Meta:
#         model = Subscriber  # Привязываем форму с конкретной моделью.
#         fields = ('subscribe_name', 'subscribe_email')

medstat/users/views.py
from django.contrib.auth import get_user_model, login
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render
from django.template.loader import render_to_string, get_template
from django.urls import reverse_lazy, reverse
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.encoding import force_bytes
from django.contrib import messages
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.shortcuts import HttpResponseRedirect
from django.http import Http404, HttpResponse
from django.core.mail import EmailMultiAlternatives
from django.core.mail import EmailMessage, get_connection

from django.views.generic import UpdateView

from .forms import RegistrationUserForm
from .models import ArticlesUser
from .tokens import account_activation_token
from rest_framework.authtoken.models import Token


# Create your views here.

class UserLoginView(LoginView):
    template_name = 'users/login.html'

class SubscribeUpdateView(LoginRequiredMixin, UpdateView):
    model = ArticlesUser
    fields = ['is_subscribed']
    template_name = 'users/subscribe.html'
    success_url = reverse_lazy('users:success_subscribe')

# @login_required
# def subscribe(request):
#     if request.method == 'GET':  # Когда мы открываем шаблон
#         form = EmailForm()
#         return render(request, 'users/subscribe.html', {'form': form})
#     else:
#         form = EmailForm(request.POST)
#         if form.is_valid():
#             # temp = form.save(commit=False)
#             # temp.subscribe_name = request.username
#             # temp.subscribe_email = request.email
#             # temp.save()
#             # обработка данных
#             # Первый способ создания формы
#             # name = form.cleaned_data['subscribe_name']
#             # email = form.cleaned_data['subscribe_email']
#             # print(f'{name}, {email}')
#             # subscriber_object = Subscriber(subscribe_name=name, subscribe_email=email, subscribe_date=datetime.now())
#             # subscriber_object.save()
#             # Второй способ создания формы
#             form.save()
#             return HttpResponseRedirect(reverse('users:success_subscribe'))
#         else:
#             return render(request, 'users/subscribe.html', {'form': form})
#
def success_subscribe(request):
        return render(request, 'users/success_subscribe.html')

# https://stackoverflow.com/questions/55578387/email-verification-in-django
# https://medium.com/@frfahim/django-registration-with-confirmation-email-bb5da011e4ef
# https://stackoverflow.com/questions/47177696/noreversematch-with-keyword-argument-uidb64-with-django-2-0
def register(request):
    # User = get_user_model()
    if request.method == 'POST':
        form = RegistrationUserForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            if ArticlesUser.objects.filter(email__iexact=email).count() == 0:
                user = form.save(commit=False)
                user.is_active = False
                user.save()
                current_site = get_current_site(request)
                mail_subject = 'Activate your account.'
                message = render_to_string('users/email_template.html', {
                            'user': user,
                            'domain': current_site.domain,
                            'uid': force_text(urlsafe_base64_encode(force_bytes(user.pk))),
                            'token': account_activation_token.make_token(user),
                        })
                print('message:', message)
                to_email = form.cleaned_data.get('email')
                # https://docs.djangoproject.com/en/2.0/topics/email/
                with get_connection() as connection:
                    EmailMessage(
                        subject=mail_subject, body=message, to=[to_email],
                        connection=connection,
                    ).send(fail_silently=False)
                # email = EmailMessage(subject=mail_subject, body=message, to=[to_email])
                # email.send(fail_silently=False)
                return render(request, 'users/acc_active_sent.html')
        else:
            return render(request, 'users/registration.html', {'form': form})
    else:
        form = RegistrationUserForm()
    return render(request, 'users/registration.html', {'form': form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = ArticlesUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, ArticlesUser.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # messages.success(request, 'Profile updated successfully')
        return HttpResponseRedirect(reverse('users:success_verification'))
    else:
        # messages.error(request, 'Error updating your profile')
        return HttpResponse('Медстатистика: Activation link is invalid!')

# https://code.tutsplus.com/ru/tutorials/using-celery-with-django-for-background-task-processing--cms-28732
def success_verification(request):
    return render(request, 'users/success_verification.html')


def get_api_token(request):
    if request.method == 'GET':
        return render(request, 'users/get_api_token.html')
    else:
        token = Token.objects.get_or_create(user=request.user)
        msg1 = 'Получение токена для работы с API'
        msg2 = 'Получение токена'
        msg3 = 'Токен предоставлен'
        return render(request, 'users/update_api_token.html', {'user': request.user, 'token': token[0], 'msg1': msg1, 'msg2': msg2, 'msg3': msg3})

def update_api_token(request):
    if request.method == 'GET':
        return render(request, 'users/update_api_token.html', {'user': request.user, 'token': '???'})
    else:
        token = Token.objects.filter(user=request.user)
        new_key = token[0].generate_key()
        token.update(key=new_key)
        msg1 = 'Обновление токена для работы с API'
        msg2 = 'Обновление токена'
        msg3 = 'Ваш токен обновлен'
        return render(request, 'users/update_api_token.html', {'user': request.user, 'token': token[0], 'msg1': msg1, 'msg2': msg2, 'msg3': msg3})


# from rest_framework.authtoken.views import ObtainAuthToken
# from rest_framework.response import Response

# class CustomObtainAuthToken(ObtainAuthToken):
#     def post(self, request, *args, **kwargs):
#         response = super(CustomObtainAuthToken, self).post(request, *args, **kwargs)
#         token = Token.objects.get(key=response.data['token'])
#         return Response({'token': token.key, 'id': token.user_id})
#
# class CustomAuthToken(ObtainAuthToken):
#
#     def post(self, request, *args, **kwargs):
#         serializer = self.serializer_class(data=request.data,
#                                            context={'request': request})
#         serializer.is_valid(raise_exception=True)
#         user = serializer.validated_data['user']
#         token, created = Token.objects.get_or_create(user=user)
#         return Response({
#             'token': token.key,
#             'user_id': user.pk,
#             'email': user.email
#         })

medstat/users/templates/users/acc_active_sent.html
{% extends 'articles/base.html' %}

{% block content %}
    <div class="site-section bg-light">
      <div class="container">
          <div class="row">
          <div class="col-md-6">
            <span>Раздел: Авторизация</span>
            <h3>Подтверждение email</h3>
            <p>Пожалуйста, подтвердите Ваш email, чтобы завершить регистрацию.</p>
          </div>
        </div>
      </div>
    </div>
<!------------------------------------------------------------------------------------------------------------------->
    <div class="site-section bg-lightx">
      <div class="container">
          <div class="text"></div>
      </div>
    </div>
{% endblock %}

medstat/users/templates/users/email.html
{% extends "articles/base.html" %}

{% block content %}
    <div class="site-section bg-light">
      <div class="container">
          <div class="row">
          <div class="col-md-12">
            <span>Раздел: Вход на сайт</span>
            <h3>Войдите или зарегистрируйтесь</h3>
            <p>Введите имя и пароль или зарегистрируйтесь</p>
          </div>
        </div>
      </div>
    </div>
    <div class="site-section bg-white">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">
            Thank you to registration!
            Hi {{ user.username }},
            we have received your details and will process soon.
        </div>
      </div>
    </div>
{% endblock content %}

medstat/users/templates/users/email_template.html
{% autoescape off %}

Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}

{% endautoescape %}

medstat/users/templates/users/get_api_token.html
{% extends "articles/base.html" %}

{% block content %}
    <div class="site-section bg-light">
      <div class="container">
          <div class="row">
          <div class="col-md-12">
            <span>Раздел: Получение токена для работы с API</span>
            <h3>Получение токена</h3>
            <p>Для получения токена нажмите кнопку "Получить токен"</p>
          </div>
        </div>
      </div>
    </div>
    <div class="site-section bg-white">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">
            <form method="post">
                {% csrf_token %}
                <button type="submit">Получить токен</button>
            </form>
        </div>
      </div>
    </div>
{% endblock content %}

medstat/users/templates/users/login.html
{% extends "articles/base.html" %}

{% block content %}
    <div class="site-section bg-light">
      <div class="container">
          <div class="row">
          <div class="col-md-12">
            <span>Раздел: Вход на сайт</span>
            <h3>Войдите или зарегистрируйтесь</h3>
            <p>Введите имя и пароль или зарегистрируйтесь</p>
          </div>
        </div>
      </div>
    </div>
    <div class="site-section bg-white">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">
            <form method="post">
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit">Войти</button>
                <br>
                <sub style="text-align: left;"><a href="{% url 'users:register' %}" style="text-decoration: none; color: blue; padding:0%; cursor:pointer; margin-right:0%;">Если у Вас нет учетной записи, загистрируйтесь!</a></sub>
            <form>
        </div>
      </div>
    </div>
{% endblock content %}

medstat/users/templates/users/registration.html
{% extends "articles/base.html" %}

{% block content %}
    <div class="site-section bg-light">
      <div class="container">
          <div class="row">
          <div class="col-md-12">
            <span>Раздел: Вход на сайт</span>
            <h3>Регистрация</h3>
            <p>Введите имя, почту и пароль</p>
          </div>
        </div>
      </div>
    </div>
    <div class="site-section bg-white">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">
            <form method="post">
                {%csrf_token%}
                <table>{{ form.as_table }}</table>
<!--                {{form.as_p}}-->
                <button type="submit">Зарегистрироваться</button>
                <sub><a href="{% url 'users:login' %}" style="text-decoration: none; color: blue; padding:1%; cursor:pointer;">Уже зарегистрированы ?</a></sub>
            </form>
        </div>
      </div>
    </div>
{% endblock content %}

medstat/users/templates/users/subscribe.html
{% extends "articles/base.html" %}

{% block title %}{{article.article_name}}{% endblock %}
<!------------------------------------------------------------------------------------------------------------------->
{% block content %}
<div class="py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
          <span>Раздел: Подписка</span>
          <h3>Подписка на новости сайта</h3>
      </div>
    </div>
  </div>
</div>

<div class="site-section bg-white">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <form method="post" enctype="multipart/form-data">
                    {%csrf_token%}
                    {{form.as_p}}
                    <button type="submit" >ОК</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
<!------------------------------------------------------------------------------------------------------------------->

medstat/users/templates/users/success_registration.html
{% extends "articles/base.html" %}

{% block content %}
    <div class="site-section bg-light">
      <div class="container">
          <div class="row">
          <div class="col-md-12">
            <span>Раздел: Вход на сайт</span>
            <h3>Регистрация</h3>
            <p>Регистрация успешно завершена. Теперь Вы можете войти на сайт.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="site-section bg-white">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">
            <form method="post">
                {%csrf_token%}
                {{form.as_p}}
            <button type="submit">Войти</button>
            <form>
        </div>
      </div>
    </div>
{% endblock %}

medstat/users/templates/users/success_subscribe.html
{% extends "articles/base.html" %}

{% block content %}
    <div class="site-section bg-light">
      <div class="container">
          <div class="row">
          <div class="col-md-12">
              <span>Раздел: Подписка</span>
              <h3>Подписка на новости сайта</h3>
              {% if user.is_subscribed %}
              <p>Подписка успешно завершена. Теперь Вы будете в курсе всех публикаций на сайте.</p>
              {% else %}
              <p>Отписка от новостей сайта успешно завершена. Но мы будем рады видеть Вас на страницах сайта.</p>
              {% endif %}
          </div>
        </div>
      </div>
    </div>
    <div class="site-section bg-white">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">
        </div>
      </div>
    </div>
{% endblock %}

medstat/users/templates/users/success_verification.html
{% extends "articles/base.html" %}

{% block content %}
    <div class="site-section bg-light">
      <div class="container">
          <div class="row">
          <div class="col-md-12">
            <span>Раздел: Вход на сайт</span>
            <h3>Верификация почты успешно завершена.</h3>
          </div>
        </div>
      </div>
    </div>
    <div class="site-section bg-white">
      <div class="container">
          <p>Приветствуем Вас, {{ user.username }}! </p>
          <p>Спасибо за регистрацию!</p>
          <p>Теперь Вы можете пользоваться всеми возможностями сайта.</p>
      </div>
    </div>
{% endblock %}

medstat/users/templates/users/update_api_token.html
{% extends "articles/base.html" %}

{% block content %}
    <div class="site-section bg-light">
      <div class="container">
          <div class="row">
          <div class="col-md-12">
            <span>Раздел: {{msg1}}</span>
            <h3>{{msg2}}</h3>
            <p>{{msg3}}</p>
          </div>
        </div>
      </div>
    </div>
    <div class="site-section bg-white">
      <div class="container">
        <div class="col-md-12">
            <p>Ваше имя: {{user.username}} </p>
            <p>Ваш e-mail: {{user.email}} </p>
            <p>Ваш токен: {{token}}</p>
            </br>
            </br>
            </br>
            <form action="/users/update_api_token/" method="post">
                {% csrf_token %}
                <button type="submit">Обновить токен</button>
            </form>
        </div>
      </div>
    </div>
{% endblock content %}