medstat/articles/urls.py
from django.contrib import admin
from django.urls import path
from articles import views

app_name = 'articles'
urlpatterns = [
    path('<int:id>/', views.article_description, name='article'),
    path('add/', views.article_add, name='article_add'),
    path('article-update/<int:pk>/', views.ArticleUpdateView.as_view(), name='article_update'),
    path('article-delete/<int:pk>/', views.ArticleDeleteView.as_view(), name='article_delete'),

    path('tag_articles/<int:id>/', views.tag_articles, name='tag_articles'),
    path('tags/', views.TagListView.as_view(), name='tag_list'),
    path('tag-one/<int:pk>/', views.TagDetailView.as_view(), name='tag_one'),
    path('tag-update/<int:pk>/', views.TagUpdateView.as_view(), name='tag_update'),
    path('tag-create/', views.TagCreateView.as_view(), name='tag_create'),
    path('tag-delete/<int:pk>/', views.TagDeleteView.as_view(), name='tag_delete'),

    path('service/', views.service, name='service'),
    path('request-service/', views.request_service, name='request_service'),
    path('request-consultation/', views.request_consultation, name='request_consultation'),
    path('request-review/', views.request_review, name='request_review'),
    path('request-question/', views.request_question, name='request_question'),
    path('success-request/', views.success_request, name='success_request'),
    path('requests/', views.ReqListView.as_view(), name='request_list'),
    path('requests_SP/', views.ReqListView_SP.as_view(), name='request_list_SP'),
    path('requests_CO/', views.ReqListView_CO.as_view(), name='request_list_CO'),
    path('requests_QS/', views.ReqListView_QS.as_view(), name='request_list_QS'),
    path('requests_RV/', views.ReqListView_RV.as_view(), name='request_list_RV'),
    path('request-update/<int:pk>/', views.ReqUpdateView.as_view(), name='request_update'),
    path('request-delete/<int:pk>/', views.ReqDeleteView.as_view(), name='request_delete'),

]

medstat/medstat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # подключаем файл настроек
from django.conf.urls.static import static  # прописываем ссылки на статик файлы
from django.conf.urls import url
from medstat import views
from rest_framework import routers
from articles.api_views import TagViewSet, ArticleViewSet, SubscriberRequestViewSet, PageHitPopularViewSet  #, PageHitViewSet
from users.api_views import InfofileViewSet  #, ArticlesUserViewSet

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register('tag', TagViewSet)
router.register('article', ArticleViewSet)
router.register('request', SubscriberRequestViewSet)
# router.register('pagehit', PageHitViewSet)
router.register('pagehit_popular', PageHitPopularViewSet)
# router.register('articles_user', ArticlesUserViewSet)
router.register('infofile', InfofileViewSet)

urlpatterns = [
    path('', views.home_page, name='home'),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('users/', include('users.urls')),
    # path('api-tag/', include('rest_framework.urls')),
    path('api/v0/', include(router.urls)),
]

if settings.DEBUG is True:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

medstat/users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('success_verification/', views.success_verification, name='success_verification'),
    path('subscribe/<int:pk>/', views.SubscribeUpdateView.as_view(), name='subscribe'),
    path('success_subscribe/', views.success_subscribe, name='success_subscribe'),
    path('get_api_token/', views.get_api_token, name='get_api_token'),
    path('update_api_token/', views.update_api_token, name='update_api_token'),
]

medstat/articles/forms.py
from django import forms
from .models import Tag
from .models import Article
from .models import SubscriberRequest

class ArticleForm(forms.ModelForm):
    article_tag = forms.ModelMultipleChoiceField(label='Тэги', queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple())
    class Meta:
        model = Article  # Привязываем форму с конкретной моделью.
        fields = '__all__'  # Все поля отображать
        # fields = ('article_name', 'article_text') # Какие поля отображать
        # exclude = ('tags')  # Какие поля исключить.

class RequestForm(forms.ModelForm):
    class Meta:
        model = SubscriberRequest  # Привязываем форму с конкретной моделью.
        # fields = '__all__'
        fields = ('subscribe_request_subject', 'subscribe_request_text')


# class ArticleForm(forms.Form):
#     name = forms.CharField(label='Название статьи', max_length=1000)
#     text = forms.CharField(label='Текст статьи')
#     tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),
#                                           widget=forms.CheckboxSelectMultiple())
# class EmailForm(forms.Form):
#     subscribe_name = forms.CharField(label='Введите Ваше имя', max_length=100)
#     subscribe_email = forms.CharField(label='Введите Ваш email', max_length=100)
# class EmailForm(forms.ModelForm):
#     class Meta:
#         model = Subscriber  # Привязываем форму с конкретной моделью.
#         fields = ('subscribe_name', 'subscribe_email')

medstat/articles/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Article, Tag, SubscriberRequest
from users.models import ArticlesUser
from .forms import ArticleForm
from .forms import RequestForm
from datetime import datetime
from django.core.files.images import ImageFile
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.decorators import method_decorator
from .decorators import counted
from django.http import Http404
from django.db.models.query import Prefetch

# Create your views (представление) here.

# prefetch_related
# https://smyt.ru/blog/django-orm/
# https://dizballanze.com/ru/django-project-optimization-part-2/

@counted
def article_description(request, id):

    art_all = Article.active_objects.defer('article_text', 'article_text_short').all()
    art_list = [id, 14, 20, 5, 12]
    art_context = []
    for art_i in art_list:
        for art_ in art_all:
            if art_.id == art_i:
                art_context.append(art_)
                break

    tags_article_all = Article.active_objects.get(id=id).article_tag.all()

    context = {
        'article': art_context[0],
        'tags_all': Tag.active_objects.all(),
        'tags_article_all': tags_article_all,
        'article_11': art_context[1],
        'article_12': art_context[2],
        'article_13': art_context[3],
        'article_14': art_context[4],
    }

    return render(request, 'articles/single.html', context)


def tag_articles(request, id):
    tag_one = get_object_or_404(Tag, id=id)
    # получаем все статьи, которые имеют тэг tag_one
    # articles_all = Article.objects.filter(article_tag__tag_name=tag_one)
    articles_all = Article.active_objects.filter(article_tag=tag_one)
    # articles_all = Article.active_objects.filter(article_tag__id=id)
    tags_all = Tag.active_objects.all()
    context = {
        'tag': tag_one,
        'articles_all': articles_all,
        'tags_all': tags_all,
        'articles_count': articles_all.count()
    }
    return render(request, 'articles/tag_articles.html', context)

@user_passes_test(lambda user: user.is_superuser)
def article_add(request):
    if request.method == 'GET':  # Когда мы открываем шаблон
        form = ArticleForm()
        return render(request, 'articles/article_add.html', {'form': form})
    else:
        form = ArticleForm(request.POST, files=request.FILES) #  POST - После отправки данных из формы
        if form.is_valid():
            # обработка данных
            # Первый способ создания формы
            # name = form.cleaned_data['name']
            # text = form.cleaned_data['text']
            # tags = form.cleaned_data['tags']
            # print(f'{name}, {text}, {tags}')
            # article_object = Article(article_name=name, article_text=text, article_date=datetime.now(), article_img=ImageFile(open("media/articles/happy_lion.jpg", "rb")))
            # article_object.save()
            # Второй способ создания формы
            form.save()
            # Переход по адресу index
            return HttpResponseRedirect(reverse('articles:index'))
        else:
            return render(request, 'articles/article_add.html', {'form': form})


def service(request):
    art_all = Article.active_objects.defer('article_text', 'article_text_short').all()
    art_list = [14, 20, 5, 12]
    art_context = []
    for art_i in art_list:
        for art_ in art_all:
            if art_.id == art_i:
                art_context.append(art_)
                break

    context = {
        'article_11': art_context[0],
        'article_12': art_context[1],
        'article_13': art_context[2],
        'article_14': art_context[3],
    }
    return render(request, 'articles/service.html', context)

@login_required
def success_request(request):
        return render(request, 'articles/success_request.html')

@login_required
def request_service(request):
    if request.method == 'GET':  # Когда мы открываем шаблон
        form = RequestForm()
        return render(request, 'articles/request_service.html', {'form': form})
    else:
        form = RequestForm(request.POST)
        if form.is_valid():
            temp = form.save(commit=False)
            temp.subscribe_request_name = request.user
            temp.subscribe_request_type = 'SP'
            temp.save()
            # form.save()
            return HttpResponseRedirect(reverse('articles:success_request'))
        else:
            return render(request, 'articles/request_service.html', {'form': form})

@login_required
def request_consultation(request):
    if request.method == 'GET':  # Когда мы открываем шаблон
        form = RequestForm()
        return render(request, 'articles/request_consultation.html', {'form': form})
    else:
        form = RequestForm(request.POST)
        if form.is_valid():
            temp = form.save(commit=False)
            temp.subscribe_request_name = request.user
            temp.subscribe_request_type = 'CO'
            temp.save()
            return HttpResponseRedirect(reverse('articles:success_request'))
        else:
            return render(request, 'articles/request_consultation.html', {'form': form})

@login_required
def request_review(request):
    if request.method == 'GET':  # Когда мы открываем шаблон
        form = RequestForm()
        return render(request, 'articles/request_review.html', {'form': form})
    else:
        form = RequestForm(request.POST)
        if form.is_valid():
            temp = form.save(commit=False)
            temp.subscribe_request_name = request.user
            temp.subscribe_request_type = 'RV'
            temp.save()
            return HttpResponseRedirect(reverse('articles:success_request'))
        else:
            return render(request, 'articles/request_review.html', {'form': form})

@login_required
def request_question(request):
    if request.method == 'GET':  # Когда мы открываем шаблон
        form = RequestForm()
        return render(request, 'articles/request_question.html', {'form': form})
    else:
        form = RequestForm(request.POST)
        if form.is_valid():
            temp = form.save(commit=False)
            temp.subscribe_request_name = request.user
            temp.subscribe_request_type = 'QS'
            temp.save()
            return HttpResponseRedirect(reverse('articles:success_request'))
        else:
            return render(request, 'articles/request_question.html', {'form': form})
#------------------------------------------------------
class PermissionMixin:
    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self): # перенаправляет пользователя на login_url
        return HttpResponseRedirect(reverse('users:login'))

# Статьи ------------------------------------------------------
class ArticleUpdateView(PermissionMixin, UserPassesTestMixin, UpdateView):
    model = Article
    fields = '__all__'
    template_name = 'articles/article_update.html'
    success_url = reverse_lazy('articles:index')

class ArticleDeleteView(PermissionMixin, UserPassesTestMixin, DeleteView):
    template_name = 'articles/article_delete.html'
    model = Article
    success_url = reverse_lazy('articles:index')

# Тэги ------------------------------------------------------
# class TagListView(LoginRequiredMixin, ListView): # Разрешает заходить авторизованному пользователю
class TagListView(PermissionMixin, UserPassesTestMixin, ListView):
    model = Tag
    template_name = 'articles/tag_list.html'
    context_object_name = 'tags'
    paginate_by = 10

    def get_queryset(self):  # наложить условия на объекты
    #     return Tag.objects.filter(is_active=True)
        return Tag.active_objects.filter()

class TagDetailView(PermissionMixin, UserPassesTestMixin, DetailView):
    model = Tag
    template_name = 'articles/tag_one.html'

class TagUpdateView(PermissionMixin, UserPassesTestMixin, UpdateView):
    model = Tag
    fields = '__all__'
    template_name = 'articles/tag_update.html'
    success_url = reverse_lazy('articles:tag_list')

class TagCreateView(PermissionMixin, UserPassesTestMixin, CreateView):
    model = Tag
    fields = '__all__'
    template_name = 'articles/tag_create.html'
    success_url = reverse_lazy('articles:tag_list')

class TagDeleteView(PermissionMixin, UserPassesTestMixin, DeleteView):
    template_name = 'articles/tag_delete.html'
    model = Tag
    success_url = reverse_lazy('articles:tag_list')

# Запросы ------------------------------------------------------
class ReqListView(PermissionMixin, UserPassesTestMixin, ListView):
    model = SubscriberRequest
    template_name = 'articles/request_list.html'
    context_object_name = 'reqs'
    paginate_by = 10

    def get_queryset(self):
    # можно наложить условия на объекты
    #     return Tag.objects.filter(is_active=True)
        return SubscriberRequest.active_objects.filter()

class ReqUpdateView(PermissionMixin, UserPassesTestMixin, UpdateView):
    model = SubscriberRequest
    fields = '__all__'
    template_name = 'articles/request_update.html'
    success_url = reverse_lazy('articles:request_list')

class ReqDeleteView(PermissionMixin, UserPassesTestMixin, DeleteView):
    template_name = 'articles/request_delete.html'
    model = SubscriberRequest
    success_url = reverse_lazy('articles:request_list')

# -------------------------------------------------------------------
class ReqListView_SP(PermissionMixin, UserPassesTestMixin, ListView):
    model = SubscriberRequest
    template_name = 'articles/request_list_SP.html'
    context_object_name = 'reqs'
    paginate_by = 10

medstat/articles/templates/articles/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>

</body>
</html>

medstat/articles/templates/articles/request_question.html
{% extends "articles/base.html" %}

{% block content %}
    <div class="site-section bg-light">
      <div class="container">
          <div class="row">
          <div class="col-md-6">
            <span>Раздел: Сервис</span>
            <h3>Задать вопрос</h3>
            <p>Опишите кратко суть Вашего вопроса и мы Вам ответим.</p>
          </div>
        </div>
      </div>
    </div>
<!------------------------------------------------------------------------------------------------------------------->
    <div class="site-section bg-white">
      <div class="container">
        <div class="col-md-12 col-lg-10">
            <p>Вы вошли как {{ user.username }}.</p>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <p>{{field.label_tag}}</p>
                <hr>
                {% for error in field.errors %}
                    {{error}}
                {% endfor %}
                <p>{{field}}</p>
                {% endfor %}
                <button type="submit" class="btn btn btn-success">Задать вопрос</button>
            </form>
            <div class="pt-5">
                <p>Если Вы хотите заказать статобработку, консультацию или рецензию, то Вы можете это сделать здесь:</p>
                <a href="{% url 'articles:request_service' %}"><span class="post-category text-white bg-success mb-3">Заказать статобработку</span></a>
                <a href="{% url 'articles:request_consultation' %}"><span class="post-category text-white bg-success mb-3">Заказать консультацию</span></a>
                <a href="{% url 'articles:request_review' %}"><span class="post-category text-white bg-success mb-3">Заказать рецензию</span></a>
                {% if user.is_authenticated %}
                  <a href="{% url 'users:subscribe' pk=user.pk %}"><span class="post-category text-white bg-success mb-3">Подписка на новости</a>
                {% else %}
                  <a href="{% url 'users:register' %}"><span class="post-category text-white bg-success mb-3">Подписка на новости</a>
                {% endif %}
            </div>
        </div>
      </div>
    </div>
{% endblock %}

medstat/articles/templates/articles/single.html
{% extends "articles/base.html" %}
{% load cache %}

{% block title %}{{article.article_name}}{% endblock %}
{% block content %}

<div class="site-cover site-cover-sm same-height overlay single-page" style="background: url({{ article.article_img.url }} ) no-repeat; background-position: center center; background-size: contain;">
<!--    https://html5book.ru/css-background/-->
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="post-entry text-center">
<!--                    <span class="post-category text-white bg-success mb-3">{{tags}}</span>-->
                    {% for tag in tags_article_all.all %}
                    <a href="{% url 'articles:tag_articles' id=tag.id %}"><span class="post-category text-white bg-primary mb-3">{{tag.tag_name}}</span></a>
                    {% empty %}
                    <p>Список тэгов у данной статьи пуст.</p>
                    {% endfor %}
                    <h2 class="mb-4"><a href="{% url 'articles:article' id=article.id %}">{{article}}</a></h2>
                        <div class="post-meta align-items-center text-center">
                            <span>&nbsp;-&nbsp; {{article.article_date|date:"d.m.Y в H:i"}} &nbsp;-&nbsp;</span>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!------------------------------------------------------------------------------------------------------------------->
    <section class="site-section py-lg">
      <div class="container">
        <div class="row blog-entries element-animate">
          <div class="col-md-12 col-lg-8 main-content">
            <div class="post-content-body">
                {{article.article_text|linebreaksbr}}
            </div>
            <div class="pt-5">
                <br>
                <h4>Задать вопрос по статье можно здесь:</h4>
                <a href="{% url 'articles:request_question' %}"><span class="post-category text-white bg-success mb-3">Задать вопрос</span></a>
                <h4>Заказать услугу можно здесь:</h4>
                <a href="{% url 'articles:request_service' %}"><span class="post-category text-white bg-success mb-3">Заказать статобработку</span></a>
                <a href="{% url 'articles:request_consultation' %}"><span class="post-category text-white bg-success mb-3">Заказать консультацию</span></a>
                <a href="{% url 'articles:request_review' %}"><span class="post-category text-white bg-success mb-3">Заказать рецензию</span></a>
                {% if user.is_authenticated %}
                  <a href="{% url 'users:subscribe' pk=user.pk %}"><span class="post-category text-white bg-success mb-3">Подписка на новости</a>
                {% else %}
                  <a href="{% url 'users:register' %}"><span class="post-category text-white bg-success mb-3">Подписка на новости</a>
                {% endif %}
            </div>
          </div>
<!------------------------------------------------------------------------------------------------------------------->
            <!-- START sidebar -->
            <div class="col-md-12 col-lg-4 sidebar">
                <div class="sidebar-box">
                  <h3 class="heading">Все тэги:</h3>
                  <ul class="tags">
                      {% cache 500 cache_tags_all %}
<!--                      {% with tags_all=article.get_all_tags %}-->
                      {% for tag_ in tags_all %}
                      <li><a href="{% url 'articles:tag_articles' id=tag_.id %}">{{tag_}} ({{tag_.art_number}})</a></li>
                      {% endfor %}
<!--                      {% endwith %}-->
                      {% endcache %}
                  </ul>
                </div>
          </div>
          <!-- END sidebar -->
<!------------------------------------------------------------------------------------------------------------------->
        </div>
      </div>
    </section>
<!------------------------------------------------------------------------------------------------------------------->
    {% if user.is_superuser %}
    <div class="site-section bg-light">
      <div class="container">
          <div class="row mb-5">
              <div class="col-12">
                  <h2>Редактирование статьи:</h2>
              </div>
          </div>
          <div class="row align-items-stretch retro-layout-2">
            <div class="text-center">
                <h5>{{article.article_name}}</h5><p></p>
                 <div class="container">
                     <div class="text-center"><a href = "{%url 'articles:article_update' pk=article.pk %}" class="btn btn-warning">Изменить</a></div><p></p>
                     <div class="text-center"><a href = "{%url 'articles:article_delete' pk=article.pk %}" class="btn btn-danger">Удалить</a></div>
                </div>
            </div>
        </div>
      </div>
    </div>
<!------------------------------------------------------------------------------------------------------------------->
    <div class="site-section bg-lightx">
      <div class="container">
          <div class="text"></div>
      </div>
    </div>
    {% endif %}
<!------------------------------------------------------------------------------------------------------------------->
<div class="site-section bg-light">
      <div class="container">
        <div class="row mb-5">
          <div class="col-12">
            <h2>Вам может понравиться</h2>
          </div>
        </div>
        <div class="row align-items-stretch retro-layout">
            <div class="col-md-5 order-md-2">
                <a href="{% url 'articles:article' id=article_11.id %}" class="hentry img-1 h-100 gradient" style="background: url({{ article_11.article_img.url }} ) no-repeat; background-size: contain;">
                  <span class="post-category text-white bg-danger">Рецензия статистика</span>
                  <div class="text">
                    <h2>{{article_11.article_name}}</h2>
                    <span>{{article_11.article_date}}</span>
                  </div>
                </a>
            </div>

          <div class="col-md-7">
            <a href="{% url 'articles:article' id=article_12.id %}" class="hentry img-2 v-height mb30 gradient" style="background: url({{ article_12.article_img.url }} ) no-repeat; background-position: center center; background-size: cover;">
              <span class="post-category text-white bg-success">Искусственный интеллект в медицине</span>
              <div class="text text-sm">
                <h2>{{article_12.article_name}}</h2>
                <span>{{article_11.article_date}}</span>
              </div>
            </a>

            <div class="two-col d-block d-md-flex">
              <a href="{% url 'articles:article' id=article_13.id %}" class="hentry v-height img-2 gradient" style="background: url({{ article_13.article_img.url }} ) no-repeat; background-size: contain;">
                <span class="post-category text-white bg-primary">Доказательная медицина</span>
                <div class="text text-sm">
                  <h2>{{article_13.article_name}}</h2>
                  <span>{{article_13.article_date}}</span>
                </div>
              </a>
              <a href="{% url 'articles:article' id=article_14.id %}" class="hentry v-height img-2 ml-auto gradient" style="background: url({{ article_14.article_img.url }} ) no-repeat; background-size: contain;">
                <span class="post-category text-white bg-warning">Визуализация</span>
                <div class="text text-sm">
                  <h2>{{article_14.article_name}}</h2>
                  <span>{{article_14.article_date}}</span>
                </div>
              </a>
            </div>
        </div>

      </div>
      </div>
</div>
{% endblock %}

medstat/articles/templates/articles/tag_articles.html
{% extends "articles/base.html" %}
{% load cache %}

{% block title %} Medstat {% endblock %}

{% block content %}
    <div class="py-5 bg-light">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <span>Раздел: Все тэги</span>
            <h3>Статьи по тэгу: {{tag.tag_name}}</h3>
            <p>Всего найдено {{articles_count}} статей. Все статьи по выбранному тэгу собраны здесь!</p>
          </div>
        </div>
      </div>
    </div>
<!------------------------------------------------------------------------------------------------------------------->
    <div class="site-section bg-white">
      <div class="container">
        <div class="row">
            {% for article in articles_all.all%}
              <div class="col-lg-4 mb-4">
                <div class="entry2">
                  <a href="{% url 'articles:article' id=article.id %}">
                    <img src="{{article.article_img.url}}" alt="Image" class="img-fluid rounded"></a>
                  <div class="excerpt">
                    <h2><a href="{% url 'articles:article' id=article.id %}">{{article.article_name}}</a></h2>
                    <div class="post-meta align-items-center text-left clearfix">
                      <span>&nbsp;-&nbsp; {{article.article_date|date:"d.m.Y в H:i"}}</span>
                    </div>
                  </div>
                </div>
              </div>
            {% empty %}
                <p>Статей по данному тэгу не найдено.</p>
            {% endfor %}
<!------------------------------------------------------------------------------------------------------------------->
            <div class="sidebar-box">
                <h3 class="heading">Все тэги:</h3>
                <ul class="tags">
                    {% cache 500 cache_tags_all %}
                    {% for tag_ in tags_all.all%}
                        <li><a href="{% url 'articles:tag_articles' id=tag_.id %}">{{tag_.tag_name}} ({{tag_.art_number}})</a></li>
                    {% empty %}
                        <li>Тэгов не найдено.</li>
                    {% endfor %}
                    {% endcache %}
                </ul>
            </div>
            <div class="pt-5">
                <h4>Заказать услугу можно здесь:</h4>
                <a href="{% url 'articles:request_service' %}"><span class="post-category text-white bg-success mb-3">Заказать статобработку</span></a>
                <a href="{% url 'articles:request_consultation' %}"><span class="post-category text-white bg-success mb-3">Заказать консультацию</span></a>
                <a href="{% url 'articles:request_review' %}"><span class="post-category text-white bg-success mb-3">Заказать рецензию</span></a>
                {% if user.is_authenticated %}
                  <a href="{% url 'users:subscribe' pk=user.pk %}"><span class="post-category text-white bg-success mb-3">Подписка на новости</a>
                {% else %}
                  <a href="{% url 'users:register' %}"><span class="post-category text-white bg-success mb-3">Подписка на новости</a>
                {% endif %}
            </div>
<!------------------------------------------------------------------------------------------------------------------->
        </div>
      </div>
    </div>
{% endblock %}

medstat/articles/templates/articles/tag_list.html
{% extends "articles/base.html" %}

{% block title %}Список тэгов{% endblock %}

{% block content %}

    <div class="py-5 bg-light">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
              <span>Раздел: Работа с тэгами</span>
              <h3>Все тэги</h3>
              <p>Наиболее актуальные тэги собраны здесь!</p>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section bg-white">
      <div class="container">
          <div class="row mb-5">
              <div class="col-12">
                  <h5>Список тэгов:</h5>
              </div>
          </div>
        <div class="row align-items-stretch retro-layout-2">
            <ul>
                {% for tag in tags%}
                <li>
                    <a href = "{%url 'articles:tag_one' pk=tag.pk %}">{{tag.tag_name}}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; первая</a>
                    <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
                {% endif %}
                <span class="current">
                    страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">следующая</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
                {% endif %}
            </span>
        </div>
        <a href="{%url 'articles:tag_create' %}" class="btn btn-primary">Добавить новый тег</a>
      </div>
    </div>
{% endblock %}